version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    groups:
      maven:
        patterns:
          - "*"

  - package-ecosystem: gradle
    directory: /intellij-plugin
    schedule:
      interval: weekly
    groups:
      gradle:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /vscode-extension
    schedule:
      interval: weekly
    groups:
      npm:
        patterns:
          - "*"
